import type { Muscle } from "./muscles";

import pecho from "@/assets/muscle-pecho.jpg";
import espalda from "@/assets/muscle-espalda.jpg";
import hombro from "@/assets/muscle-hombro.jpg";
import biceps from "@/assets/muscle-biceps.jpg";
import triceps from "@/assets/muscle-triceps.jpg";
import antebrazos from "@/assets/muscle-antebrazos.jpg";
import abdominales from "@/assets/muscle-abdominales.jpg";
import gluteos from "@/assets/muscle-gluteos.jpg";
import cuadriceps from "@/assets/muscle-cuadriceps.jpg";
import isquiotibiales from "@/assets/muscle-isquiotibiales.jpg";
import pantorrillas from "@/assets/muscle-pantorrillas.jpg";
import cardio from "@/assets/muscle-cardio.jpg";
import estiramientos from "@/assets/muscle-estiramientos.jpg";

export const MUSCLE_IMAGE: Record<Muscle, string> = {
  Pecho: pecho,
  Espalda: espalda,
  Hombro: hombro,
  "Bíceps": biceps,
  "Tríceps": triceps,
  Antebrazos: antebrazos,
  Abdominales: abdominales,
  Core: abdominales,
  "Glúteos": gluteos,
  "Cuádriceps": cuadriceps,
  Isquiotibiales: isquiotibiales,
  Pantorrillas: pantorrillas,
  Cardio: cardio,
  Estiramientos: estiramientos,
};

export type CatalogExercise = { name: string };

export const EXERCISE_CATALOG: Record<Muscle, CatalogExercise[]> = {
  Pecho: [
    { name: "Press de banca" },
    { name: "Press de banca agarre cerrado" },
    { name: "Press inclinado con barra" },
    { name: "Press inclinado mancuernas" },
    { name: "Press declinado con barra" },
    { name: "Press declinado mancuernas" },
    { name: "Press con mancuernas plano" },
    { name: "Press en máquina" },
    { name: "Press Smith plano" },
    { name: "Press Smith inclinado" },
    { name: "Aperturas con mancuernas" },
    { name: "Aperturas inclinadas con mancuernas" },
    { name: "Aperturas declinadas" },
    { name: "Aperturas en máquina (peck deck)" },
    { name: "Cruce de poleas alto" },
    { name: "Cruce de poleas medio" },
    { name: "Cruce de poleas bajo" },
    { name: "Fondos en paralelas (pecho)" },
    { name: "Fondos asistidos en máquina" },
    { name: "Push up (flexiones)" },
    { name: "Push up declinado" },
    { name: "Push up inclinado" },
    { name: "Push up diamante" },
    { name: "Push up con palmada" },
    { name: "Pullover con mancuerna" },
    { name: "Pullover en polea" },
    { name: "Press en suelo (floor press)" },
    { name: "Svend press" },
  ],
  Espalda: [
    { name: "Peso muerto convencional" },
    { name: "Peso muerto sumo" },
    { name: "Peso muerto con trap bar" },
    { name: "Remo con barra" },
    { name: "Remo Pendlay" },
    { name: "Remo Yates (agarre supino)" },
    { name: "Remo con mancuerna a una mano" },
    { name: "Remo en máquina" },
    { name: "Remo en T" },
    { name: "Remo con barra apoyado en banco" },
    { name: "Remo invertido" },
    { name: "Remo en polea baja" },
    { name: "Remo en polea con agarre ancho" },
    { name: "Hiperextensiones" },
    { name: "Hiperextensiones con peso" },
    { name: "Reverse hyper" },
    { name: "Good morning" },
    { name: "Face pull" },
    { name: "Encogimientos con barra" },
    { name: "Encogimientos con mancuernas" },
    { name: "Rack pulls" },
    { name: "Superman" },
    { name: "Dominadas pronas" },
    { name: "Dominadas supinas (chin up)" },
    { name: "Dominadas neutras" },
    { name: "Dominadas con peso" },
    { name: "Dominadas asistidas" },
    { name: "Jalón al pecho agarre ancho" },
    { name: "Jalón al pecho agarre cerrado" },
    { name: "Jalón agarre supino" },
    { name: "Jalón a una mano" },
    { name: "Jalón con cuerda" },
    { name: "Pullover con mancuerna" },
    { name: "Pullover en polea (straight arm)" },
    { name: "Remo Meadows" },
    { name: "Kroc rows" },
    { name: "Pull over en máquina" },
  ],
  Hombro: [
    { name: "Press militar con barra de pie" },
    { name: "Press militar sentado" },
    { name: "Press con mancuernas sentado" },
    { name: "Press Arnold" },
    { name: "Press en máquina" },
    { name: "Push press" },
    { name: "Elevaciones laterales con mancuernas" },
    { name: "Elevaciones laterales en polea" },
    { name: "Elevaciones laterales en máquina" },
    { name: "Elevaciones laterales inclinado" },
    { name: "Elevaciones frontales con mancuernas" },
    { name: "Elevaciones frontales con barra" },
    { name: "Elevaciones frontales en polea" },
    { name: "Elevación frontal con disco" },
    { name: "Pájaros con mancuernas" },
    { name: "Pájaros en banco inclinado" },
    { name: "Posterior en máquina (reverse fly)" },
    { name: "Face pull" },
    { name: "Remo al mentón con barra" },
    { name: "Remo al mentón con mancuernas" },
    { name: "Encogimientos con barra" },
    { name: "Encogimientos con mancuernas" },
    { name: "Handstand push up" },
    { name: "Cuban press" },
  ],
  "Bíceps": [
    { name: "Curl con barra recta" },
    { name: "Curl con barra Z" },
    { name: "Curl con mancuernas" },
    { name: "Curl alterno con mancuernas" },
    { name: "Curl martillo" },
    { name: "Curl martillo en cuerda" },
    { name: "Curl predicador con barra" },
    { name: "Curl predicador con mancuerna" },
    { name: "Curl concentrado" },
    { name: "Curl en polea baja" },
    { name: "Curl en polea alta (doble bíceps)" },
    { name: "Curl Spider" },
    { name: "Curl inclinado con mancuernas" },
    { name: "Curl Zottman" },
    { name: "Curl 21s" },
    { name: "Curl en máquina" },
    { name: "Chin up (dominada supina)" },
    { name: "Curl arrastre (drag curl)" },
  ],
  "Tríceps": [
    { name: "Press francés con barra" },
    { name: "Press francés con mancuernas" },
    { name: "Extensiones en polea con barra" },
    { name: "Extensiones en polea con cuerda" },
    { name: "Extensiones en polea agarre invertido" },
    { name: "Fondos en banco" },
    { name: "Fondos en paralelas (tríceps)" },
    { name: "Patada de tríceps con mancuerna" },
    { name: "Patada de tríceps en polea" },
    { name: "Press cerrado en banca" },
    { name: "Extensiones sobre cabeza con mancuerna" },
    { name: "Extensiones sobre cabeza con cuerda" },
    { name: "Extensiones sobre cabeza con barra Z" },
    { name: "JM press" },
    { name: "Skull crushers" },
    { name: "Tate press" },
    { name: "Diamond push up" },
    { name: "Tríceps en máquina" },
  ],
  Antebrazos: [
    { name: "Curl de muñeca con barra" },
    { name: "Curl de muñeca con mancuernas" },
    { name: "Curl de muñeca invertido" },
    { name: "Curl invertido con barra" },
    { name: "Curl Zottman" },
    { name: "Farmer walk" },
    { name: "Suspensión en barra (dead hang)" },
    { name: "Plate pinch" },
    { name: "Wrist roller" },
    { name: "Hammer curl" },
    { name: "Behind-the-back wrist curl" },
  ],
  Abdominales: [
    { name: "Crunch" },
    { name: "Crunch en polea" },
    { name: "Crunch en máquina" },
    { name: "Crunch inverso" },
    { name: "Crunch en bicicleta" },
    { name: "Sit up" },
    { name: "V-up" },
    { name: "Toes to bar" },
    { name: "Elevación de piernas colgado" },
    { name: "Elevación de rodillas colgado" },
    { name: "Elevación de piernas tumbado" },
    { name: "Rueda abdominal (ab wheel)" },
    { name: "Hollow hold" },
    { name: "Dragon flag" },
    { name: "Cable woodchopper" },
  ],
  Core: [
    { name: "Plancha frontal" },
    { name: "Plancha lateral" },
    { name: "Plancha con elevación" },
    { name: "Russian twist" },
    { name: "Russian twist con peso" },
    { name: "Mountain climbers" },
    { name: "Dead bug" },
    { name: "Bird dog" },
    { name: "Pallof press" },
    { name: "Cable woodchopper" },
    { name: "Hollow body hold" },
    { name: "Copenhagen plank" },
    { name: "L-sit" },
    { name: "Suitcase carry" },
    { name: "Turkish get up" },
  ],
  "Glúteos": [
    { name: "Hip thrust con barra" },
    { name: "Hip thrust en máquina" },
    { name: "Glute bridge" },
    { name: "Glute bridge a una pierna" },
    { name: "Patada de glúteo en polea" },
    { name: "Patada de glúteo en máquina" },
    { name: "Sentadilla búlgara" },
    { name: "Sentadilla sumo" },
    { name: "Peso muerto rumano" },
    { name: "Peso muerto rumano a una pierna" },
    { name: "Abductor en máquina" },
    { name: "Abducción en polea" },
    { name: "Step up" },
    { name: "Zancadas inversas" },
    { name: "Zancadas caminando" },
    { name: "Cable pull through" },
    { name: "Frog pump" },
    { name: "Hip abduction de pie" },
  ],
  "Cuádriceps": [
    { name: "Sentadilla con barra" },
    { name: "Sentadilla frontal" },
    { name: "Sentadilla goblet" },
    { name: "Sentadilla búlgara" },
    { name: "Sentadilla sissy" },
    { name: "Sentadilla en Smith" },
    { name: "Hack squat" },
    { name: "Prensa de piernas" },
    { name: "Prensa horizontal" },
    { name: "Extensiones de cuádriceps" },
    { name: "Extensiones a una pierna" },
    { name: "Zancadas con mancuernas" },
    { name: "Zancadas con barra" },
    { name: "Zancadas caminando" },
    { name: "Step up con mancuernas" },
    { name: "Pistol squat" },
    { name: "Box squat" },
    { name: "Wall sit" },
    { name: "Belt squat" },
  ],
  Isquiotibiales: [
    { name: "Curl femoral tumbado" },
    { name: "Curl femoral sentado" },
    { name: "Curl femoral de pie" },
    { name: "Buenos días con barra" },
    { name: "Peso muerto rumano" },
    { name: "Peso muerto piernas rígidas" },
    { name: "Peso muerto a una pierna" },
    { name: "Curl nórdico" },
    { name: "Glute ham raise" },
    { name: "Hiperextensiones (énfasis isquios)" },
    { name: "Kettlebell swing" },
    { name: "Reverse hyper" },
    { name: "Slider leg curl" },
  ],
  Pantorrillas: [
    { name: "Elevación de talones de pie con barra" },
    { name: "Elevación de talones de pie en máquina" },
    { name: "Elevación de talones sentado" },
    { name: "Pantorrilla en prensa" },
    { name: "Elevación de talones a una pierna" },
    { name: "Donkey calf raise" },
    { name: "Saltos a la comba" },
    { name: "Saltos al cajón" },
    { name: "Tibial anterior" },
    { name: "Farmer walk en puntillas" },
  ],
  Cardio: [
    { name: "Cinta de correr" },
    { name: "Cinta inclinada (caminata)" },
    { name: "Bicicleta estática" },
    { name: "Bicicleta de spinning" },
    { name: "Bicicleta reclinada" },
    { name: "Elíptica" },
    { name: "Remo (rower)" },
    { name: "Escaladora (stair master)" },
    { name: "Ski erg" },
    { name: "Assault bike" },
    { name: "HIIT" },
    { name: "Sprints" },
    { name: "Burpees" },
    { name: "Jumping jacks" },
    { name: "Saltos a la comba" },
    { name: "Battle ropes" },
    { name: "Box jumps" },
    { name: "Mountain climbers" },
    { name: "Sled push" },
  ],
  Estiramientos: [
    { name: "Estiramiento de isquiotibiales de pie" },
    { name: "Estiramiento de isquiotibiales sentado" },
    { name: "Estiramiento de cuádriceps de pie" },
    { name: "Estiramiento de flexores de cadera (zancada)" },
    { name: "Estiramiento de glúteo (figura 4)" },
    { name: "Estiramiento de piriforme tumbado" },
    { name: "Estiramiento de aductores (mariposa)" },
    { name: "Estiramiento de gemelos en pared" },
    { name: "Estiramiento de sóleo" },
    { name: "Estiramiento de pectoral en marco de puerta" },
    { name: "Estiramiento de dorsales colgado en barra" },
    { name: "Estiramiento de tríceps sobre cabeza" },
    { name: "Estiramiento de hombro cruzado" },
    { name: "Estiramiento de cuello lateral" },
    { name: "Postura del niño (child pose)" },
    { name: "Gato-camello (cat-cow)" },
    { name: "Postura del perro boca abajo" },
    { name: "Cobra (estiramiento lumbar)" },
    { name: "Torsión espinal tumbado" },
    { name: "Estiramiento de antebrazos y muñecas" },
    { name: "Estiramiento de banda iliotibial" },
    { name: "Movilidad de cadera 90/90" },
  ],
};
