import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export const LANGUAGES = [
  { code: "es", name: "Español", country: "es" },
  { code: "en", name: "English", country: "gb" },
  { code: "fr", name: "Français", country: "fr" },
  { code: "de", name: "Deutsch", country: "de" },
  { code: "it", name: "Italiano", country: "it" },
  { code: "pt", name: "Português", country: "pt" },
  { code: "nl", name: "Nederlands", country: "nl" },
  { code: "ru", name: "Русский", country: "ru" },
  { code: "zh", name: "中文", country: "cn" },
  { code: "ja", name: "日本語", country: "jp" },
  { code: "ko", name: "한국어", country: "kr" },
  { code: "ar", name: "العربية", country: "sa" },
  { code: "hi", name: "हिन्दी", country: "in" },
  { code: "tr", name: "Türkçe", country: "tr" },
  { code: "pl", name: "Polski", country: "pl" },
  { code: "sv", name: "Svenska", country: "se" },
  { code: "no", name: "Norsk", country: "no" },
  { code: "da", name: "Dansk", country: "dk" },
  { code: "fi", name: "Suomi", country: "fi" },
  { code: "cs", name: "Čeština", country: "cz" },
  { code: "el", name: "Ελληνικά", country: "gr" },
  { code: "he", name: "עברית", country: "il" },
  { code: "id", name: "Bahasa Indonesia", country: "id" },
  { code: "th", name: "ไทย", country: "th" },
  { code: "vi", name: "Tiếng Việt", country: "vn" },
  { code: "uk", name: "Українська", country: "ua" },
  { code: "ro", name: "Română", country: "ro" },
  { code: "hu", name: "Magyar", country: "hu" },
  { code: "bg", name: "Български", country: "bg" },
  { code: "ca", name: "Català", country: "es-ct" },
] as const;

export type LangCode = (typeof LANGUAGES)[number]["code"];

export function flagUrl(country: string, size: 24 | 48 = 48) {
  return `https://flagcdn.com/${size === 24 ? "w40" : "w80"}/${country}.png`;
}

type Dict = {
  training: string; health: string; logout: string;
  age: string; height: string; weight: string; save: string;
  bmi: string; bmiChartTitle: string; ideal: string; you: string;
  underweight: string; normal: string; overweight: string; obese: string;
  healthIntro: string; language: string;
  // Login
  signin: string; signup: string; email: string; password: string;
  name: string; namePh: string; emailPh: string; passwordPh: string;
  continueGoogle: string; or: string; loading: string;
  brandTag: string; accountCreated: string; errorGeneric: string; googleError: string;
  // Optional (fall back to es)
  forgotPassword?: string; resetEmailSent?: string; resetEmailPrompt?: string;
  nutrition?: string; healthyFood?: string; calorieCounter?: string;
  breakfast?: string; lunch?: string; snack?: string; dinner?: string;
  goal?: string; goalCut?: string; goalBulk?: string; goalLose?: string; goalMaintain?: string;
  activity?: string; act1?: string; act2?: string; act3?: string; act4?: string; act5?: string;
  sex?: string; male?: string; female?: string;
  targetWeight?: string; calculate?: string; yourPlan?: string;
  dailyCalories?: string; protein?: string; carbs?: string; fats?: string;
  mealsBreakdown?: string; tips?: string;
  maintenanceTitle?: string; maintenanceBody?: string; retry?: string; checkingServer?: string;
};

const T: Record<LangCode, Dict> = {
  es: { training: "Entrenamiento", health: "Salud", logout: "Salir", age: "Edad", height: "Altura (cm)", weight: "Peso (kg)", save: "Guardar", bmi: "IMC", bmiChartTitle: "Tu IMC vs. rango ideal", ideal: "Ideal", you: "Tú", underweight: "Bajo peso", normal: "Normal", overweight: "Sobrepeso", obese: "Obesidad", healthIntro: "Completa tus datos para calcular tu IMC.", language: "Idioma", signin: "Entrar", signup: "Crear cuenta", email: "Email", password: "Contraseña", name: "Nombre", namePh: "Tu nombre", emailPh: "tu@email.com", passwordPh: "••••••••", continueGoogle: "Continuar con Google", or: "o", loading: "Cargando...", brandTag: "tu plan, tu progreso", accountCreated: "Cuenta creada. Revisa tu email para confirmar.", errorGeneric: "Error", googleError: "No se pudo iniciar sesión con Google", forgotPassword: "Olvidé mi contraseña", resetEmailSent: "Te hemos enviado un email para restablecer tu contraseña.", resetEmailPrompt: "Introduce tu email arriba y pulsa de nuevo.", nutrition: "Nutrición", healthyFood: "Comida saludable", calorieCounter: "Cuenta calorías", breakfast: "Desayuno", lunch: "Comida", snack: "Merienda", dinner: "Cena", goal: "Objetivo", goalCut: "Definir", goalBulk: "Ganar músculo", goalLose: "Perder grasa", goalMaintain: "Mantener", activity: "Actividad física", act1: "Sedentario (poco o nada)", act2: "Ligera (1-3 días/sem)", act3: "Moderada (3-5 días/sem)", act4: "Alta (6-7 días/sem)", act5: "Muy alta (2x al día)", sex: "Sexo", male: "Hombre", female: "Mujer", targetWeight: "Peso objetivo (kg)", calculate: "Calcular dieta", yourPlan: "Tu plan", dailyCalories: "Calorías diarias", protein: "Proteína", carbs: "Carbohidratos", fats: "Grasas", mealsBreakdown: "Reparto por comida", tips: "Consejos" },
  en: { training: "Training", health: "Health", logout: "Sign out", age: "Age", height: "Height (cm)", weight: "Weight (kg)", save: "Save", bmi: "BMI", bmiChartTitle: "Your BMI vs. ideal range", ideal: "Ideal", you: "You", underweight: "Underweight", normal: "Normal", overweight: "Overweight", obese: "Obese", healthIntro: "Fill in your data to calculate your BMI.", language: "Language", signin: "Sign in", signup: "Sign up", email: "Email", password: "Password", name: "Name", namePh: "Your name", emailPh: "you@email.com", passwordPh: "••••••••", continueGoogle: "Continue with Google", or: "or", loading: "Loading...", brandTag: "your plan, your progress", accountCreated: "Account created. Check your email to confirm.", errorGeneric: "Error", googleError: "Could not sign in with Google", forgotPassword: "Forgot password?", resetEmailSent: "We sent you a password reset email.", resetEmailPrompt: "Enter your email above and click again.", nutrition: "Nutrition", healthyFood: "Healthy food", calorieCounter: "Calorie counter", breakfast: "Breakfast", lunch: "Lunch", snack: "Snack", dinner: "Dinner", goal: "Goal", goalCut: "Cut / definition", goalBulk: "Build muscle", goalLose: "Lose fat", goalMaintain: "Maintain", activity: "Activity level", act1: "Sedentary (little or none)", act2: "Light (1-3 days/wk)", act3: "Moderate (3-5 days/wk)", act4: "High (6-7 days/wk)", act5: "Very high (twice a day)", sex: "Sex", male: "Male", female: "Female", targetWeight: "Target weight (kg)", calculate: "Calculate diet", yourPlan: "Your plan", dailyCalories: "Daily calories", protein: "Protein", carbs: "Carbs", fats: "Fats", mealsBreakdown: "Meal breakdown", tips: "Tips" },
  fr: { training: "Entraînement", health: "Santé", logout: "Déconnexion", age: "Âge", height: "Taille (cm)", weight: "Poids (kg)", save: "Enregistrer", bmi: "IMC", bmiChartTitle: "Votre IMC vs. plage idéale", ideal: "Idéal", you: "Vous", underweight: "Maigreur", normal: "Normal", overweight: "Surpoids", obese: "Obésité", healthIntro: "Remplissez vos données pour calculer votre IMC.", language: "Langue", signin: "Se connecter", signup: "S'inscrire", email: "Email", password: "Mot de passe", name: "Nom", namePh: "Votre nom", emailPh: "vous@email.com", passwordPh: "••••••••", continueGoogle: "Continuer avec Google", or: "ou", loading: "Chargement...", brandTag: "votre plan, votre progrès", accountCreated: "Compte créé. Vérifiez votre email.", errorGeneric: "Erreur", googleError: "Échec de connexion Google" },
  de: { training: "Training", health: "Gesundheit", logout: "Abmelden", age: "Alter", height: "Größe (cm)", weight: "Gewicht (kg)", save: "Speichern", bmi: "BMI", bmiChartTitle: "Dein BMI vs. Idealbereich", ideal: "Ideal", you: "Du", underweight: "Untergewicht", normal: "Normal", overweight: "Übergewicht", obese: "Adipositas", healthIntro: "Gib deine Daten ein, um deinen BMI zu berechnen.", language: "Sprache", signin: "Anmelden", signup: "Registrieren", email: "Email", password: "Passwort", name: "Name", namePh: "Dein Name", emailPh: "du@email.com", passwordPh: "••••••••", continueGoogle: "Mit Google fortfahren", or: "oder", loading: "Lädt...", brandTag: "dein Plan, dein Fortschritt", accountCreated: "Konto erstellt. E-Mail prüfen.", errorGeneric: "Fehler", googleError: "Google-Anmeldung fehlgeschlagen" },
  it: { training: "Allenamento", health: "Salute", logout: "Esci", age: "Età", height: "Altezza (cm)", weight: "Peso (kg)", save: "Salva", bmi: "IMC", bmiChartTitle: "Il tuo IMC vs. intervallo ideale", ideal: "Ideale", you: "Tu", underweight: "Sottopeso", normal: "Normale", overweight: "Sovrappeso", obese: "Obesità", healthIntro: "Inserisci i tuoi dati per calcolare l'IMC.", language: "Lingua", signin: "Accedi", signup: "Registrati", email: "Email", password: "Password", name: "Nome", namePh: "Il tuo nome", emailPh: "tu@email.com", passwordPh: "••••••••", continueGoogle: "Continua con Google", or: "o", loading: "Caricamento...", brandTag: "il tuo piano, i tuoi progressi", accountCreated: "Account creato. Controlla la tua email.", errorGeneric: "Errore", googleError: "Accesso Google fallito" },
  pt: { training: "Treino", health: "Saúde", logout: "Sair", age: "Idade", height: "Altura (cm)", weight: "Peso (kg)", save: "Guardar", bmi: "IMC", bmiChartTitle: "O teu IMC vs. faixa ideal", ideal: "Ideal", you: "Você", underweight: "Abaixo do peso", normal: "Normal", overweight: "Sobrepeso", obese: "Obesidade", healthIntro: "Preencha os seus dados para calcular o IMC.", language: "Idioma", signin: "Entrar", signup: "Criar conta", email: "Email", password: "Senha", name: "Nome", namePh: "Seu nome", emailPh: "voce@email.com", passwordPh: "••••••••", continueGoogle: "Continuar com Google", or: "ou", loading: "A carregar...", brandTag: "o seu plano, o seu progresso", accountCreated: "Conta criada. Verifique o email.", errorGeneric: "Erro", googleError: "Falha no Google" },
  nl: { training: "Training", health: "Gezondheid", logout: "Uitloggen", age: "Leeftijd", height: "Lengte (cm)", weight: "Gewicht (kg)", save: "Opslaan", bmi: "BMI", bmiChartTitle: "Jouw BMI vs. ideaal bereik", ideal: "Ideaal", you: "Jij", underweight: "Ondergewicht", normal: "Normaal", overweight: "Overgewicht", obese: "Obesitas", healthIntro: "Vul je gegevens in om je BMI te berekenen.", language: "Taal", signin: "Inloggen", signup: "Registreren", email: "Email", password: "Wachtwoord", name: "Naam", namePh: "Jouw naam", emailPh: "jij@email.com", passwordPh: "••••••••", continueGoogle: "Doorgaan met Google", or: "of", loading: "Laden...", brandTag: "jouw plan, jouw voortgang", accountCreated: "Account aangemaakt. Check je email.", errorGeneric: "Fout", googleError: "Google-aanmelding mislukt" },
  ru: { training: "Тренировка", health: "Здоровье", logout: "Выйти", age: "Возраст", height: "Рост (см)", weight: "Вес (кг)", save: "Сохранить", bmi: "ИМТ", bmiChartTitle: "Ваш ИМТ vs. идеальный диапазон", ideal: "Идеальный", you: "Вы", underweight: "Недостаток", normal: "Норма", overweight: "Избыток", obese: "Ожирение", healthIntro: "Заполните данные для расчёта ИМТ.", language: "Язык", signin: "Войти", signup: "Регистрация", email: "Email", password: "Пароль", name: "Имя", namePh: "Ваше имя", emailPh: "вы@email.com", passwordPh: "••••••••", continueGoogle: "Войти через Google", or: "или", loading: "Загрузка...", brandTag: "ваш план, ваш прогресс", accountCreated: "Аккаунт создан. Проверьте email.", errorGeneric: "Ошибка", googleError: "Ошибка входа Google" },
  zh: { training: "训练", health: "健康", logout: "退出", age: "年龄", height: "身高 (厘米)", weight: "体重 (公斤)", save: "保存", bmi: "BMI", bmiChartTitle: "你的 BMI 与理想范围", ideal: "理想", you: "你", underweight: "偏瘦", normal: "正常", overweight: "超重", obese: "肥胖", healthIntro: "填写数据以计算你的 BMI。", language: "语言", signin: "登录", signup: "注册", email: "邮箱", password: "密码", name: "姓名", namePh: "你的名字", emailPh: "you@email.com", passwordPh: "••••••••", continueGoogle: "使用 Google 继续", or: "或", loading: "加载中...", brandTag: "你的计划，你的进步", accountCreated: "账号已创建，请检查邮箱。", errorGeneric: "错误", googleError: "Google 登录失败" },
  ja: { training: "トレーニング", health: "健康", logout: "ログアウト", age: "年齢", height: "身長 (cm)", weight: "体重 (kg)", save: "保存", bmi: "BMI", bmiChartTitle: "あなたの BMI と理想範囲", ideal: "理想", you: "あなた", underweight: "低体重", normal: "標準", overweight: "過体重", obese: "肥満", healthIntro: "データを入力して BMI を計算しましょう。", language: "言語", signin: "ログイン", signup: "登録", email: "メール", password: "パスワード", name: "名前", namePh: "あなたの名前", emailPh: "you@email.com", passwordPh: "••••••••", continueGoogle: "Google で続行", or: "または", loading: "読み込み中...", brandTag: "あなたのプラン、あなたの進歩", accountCreated: "アカウント作成。メールを確認。", errorGeneric: "エラー", googleError: "Google ログイン失敗" },
  ko: { training: "운동", health: "건강", logout: "로그아웃", age: "나이", height: "키 (cm)", weight: "몸무게 (kg)", save: "저장", bmi: "BMI", bmiChartTitle: "당신의 BMI 대 이상 범위", ideal: "이상", you: "당신", underweight: "저체중", normal: "정상", overweight: "과체중", obese: "비만", healthIntro: "데이터를 입력하여 BMI를 계산하세요.", language: "언어", signin: "로그인", signup: "회원가입", email: "이메일", password: "비밀번호", name: "이름", namePh: "이름", emailPh: "you@email.com", passwordPh: "••••••••", continueGoogle: "Google로 계속", or: "또는", loading: "로딩...", brandTag: "당신의 계획, 당신의 진보", accountCreated: "계정 생성됨. 이메일 확인.", errorGeneric: "오류", googleError: "Google 로그인 실패" },
  ar: { training: "تدريب", health: "صحة", logout: "خروج", age: "العمر", height: "الطول (سم)", weight: "الوزن (كجم)", save: "حفظ", bmi: "مؤشر الكتلة", bmiChartTitle: "مؤشرك مقابل النطاق المثالي", ideal: "مثالي", you: "أنت", underweight: "نقص الوزن", normal: "طبيعي", overweight: "زيادة الوزن", obese: "سمنة", healthIntro: "أدخل بياناتك لحساب مؤشر كتلة جسمك.", language: "اللغة", signin: "دخول", signup: "إنشاء حساب", email: "البريد", password: "كلمة المرور", name: "الاسم", namePh: "اسمك", emailPh: "you@email.com", passwordPh: "••••••••", continueGoogle: "المتابعة بـ Google", or: "أو", loading: "جارٍ التحميل...", brandTag: "خطتك، تقدمك", accountCreated: "تم إنشاء الحساب. تحقق من بريدك.", errorGeneric: "خطأ", googleError: "فشل تسجيل Google" },
  hi: { training: "प्रशिक्षण", health: "स्वास्थ्य", logout: "लॉग आउट", age: "उम्र", height: "ऊँचाई (सेमी)", weight: "वज़न (किग्रा)", save: "सहेजें", bmi: "BMI", bmiChartTitle: "आपका BMI बनाम आदर्श", ideal: "आदर्श", you: "आप", underweight: "कम वज़न", normal: "सामान्य", overweight: "अधिक वज़न", obese: "मोटापा", healthIntro: "अपना BMI जानने के लिए डेटा भरें।", language: "भाषा", signin: "साइन इन", signup: "साइन अप", email: "ईमेल", password: "पासवर्ड", name: "नाम", namePh: "आपका नाम", emailPh: "you@email.com", passwordPh: "••••••••", continueGoogle: "Google के साथ जारी रखें", or: "या", loading: "लोड हो रहा है...", brandTag: "आपकी योजना, आपकी प्रगति", accountCreated: "खाता बना। ईमेल देखें।", errorGeneric: "त्रुटि", googleError: "Google साइन इन विफल" },
  tr: { training: "Antrenman", health: "Sağlık", logout: "Çıkış", age: "Yaş", height: "Boy (cm)", weight: "Kilo (kg)", save: "Kaydet", bmi: "VKİ", bmiChartTitle: "VKİ'niz vs. ideal aralık", ideal: "İdeal", you: "Sen", underweight: "Zayıf", normal: "Normal", overweight: "Fazla kilolu", obese: "Obez", healthIntro: "VKİ'nizi hesaplamak için verilerinizi girin.", language: "Dil", signin: "Giriş", signup: "Kayıt ol", email: "Email", password: "Şifre", name: "İsim", namePh: "Adınız", emailPh: "siz@email.com", passwordPh: "••••••••", continueGoogle: "Google ile devam et", or: "veya", loading: "Yükleniyor...", brandTag: "planın, ilerlemen", accountCreated: "Hesap oluşturuldu. Email kontrol edin.", errorGeneric: "Hata", googleError: "Google girişi başarısız" },
  pl: { training: "Trening", health: "Zdrowie", logout: "Wyloguj", age: "Wiek", height: "Wzrost (cm)", weight: "Waga (kg)", save: "Zapisz", bmi: "BMI", bmiChartTitle: "Twoje BMI vs. zakres idealny", ideal: "Idealne", you: "Ty", underweight: "Niedowaga", normal: "Norma", overweight: "Nadwaga", obese: "Otyłość", healthIntro: "Wypełnij dane, aby obliczyć BMI.", language: "Język", signin: "Zaloguj", signup: "Zarejestruj", email: "Email", password: "Hasło", name: "Imię", namePh: "Twoje imię", emailPh: "ty@email.com", passwordPh: "••••••••", continueGoogle: "Kontynuuj z Google", or: "lub", loading: "Ładowanie...", brandTag: "twój plan, twój postęp", accountCreated: "Konto utworzone. Sprawdź email.", errorGeneric: "Błąd", googleError: "Logowanie Google nieudane" },
  sv: { training: "Träning", health: "Hälsa", logout: "Logga ut", age: "Ålder", height: "Längd (cm)", weight: "Vikt (kg)", save: "Spara", bmi: "BMI", bmiChartTitle: "Ditt BMI vs. idealområde", ideal: "Ideal", you: "Du", underweight: "Undervikt", normal: "Normal", overweight: "Övervikt", obese: "Fetma", healthIntro: "Fyll i dina uppgifter för att beräkna BMI.", language: "Språk", signin: "Logga in", signup: "Registrera", email: "Email", password: "Lösenord", name: "Namn", namePh: "Ditt namn", emailPh: "du@email.com", passwordPh: "••••••••", continueGoogle: "Fortsätt med Google", or: "eller", loading: "Laddar...", brandTag: "din plan, din utveckling", accountCreated: "Konto skapat. Kolla email.", errorGeneric: "Fel", googleError: "Google-inloggning misslyckades" },
  no: { training: "Trening", health: "Helse", logout: "Logg ut", age: "Alder", height: "Høyde (cm)", weight: "Vekt (kg)", save: "Lagre", bmi: "BMI", bmiChartTitle: "Din BMI vs. idealområde", ideal: "Ideell", you: "Du", underweight: "Undervekt", normal: "Normal", overweight: "Overvekt", obese: "Fedme", healthIntro: "Fyll inn data for å beregne BMI.", language: "Språk", signin: "Logg inn", signup: "Registrer", email: "Email", password: "Passord", name: "Navn", namePh: "Ditt navn", emailPh: "du@email.com", passwordPh: "••••••••", continueGoogle: "Fortsett med Google", or: "eller", loading: "Laster...", brandTag: "din plan, din fremgang", accountCreated: "Konto opprettet. Sjekk email.", errorGeneric: "Feil", googleError: "Google-innlogging mislyktes" },
  da: { training: "Træning", health: "Sundhed", logout: "Log ud", age: "Alder", height: "Højde (cm)", weight: "Vægt (kg)", save: "Gem", bmi: "BMI", bmiChartTitle: "Din BMI vs. idealområde", ideal: "Ideel", you: "Du", underweight: "Undervægt", normal: "Normal", overweight: "Overvægt", obese: "Fedme", healthIntro: "Udfyld dine data for at beregne BMI.", language: "Sprog", signin: "Log ind", signup: "Tilmeld", email: "Email", password: "Adgangskode", name: "Navn", namePh: "Dit navn", emailPh: "du@email.com", passwordPh: "••••••••", continueGoogle: "Fortsæt med Google", or: "eller", loading: "Indlæser...", brandTag: "din plan, din fremgang", accountCreated: "Konto oprettet. Tjek email.", errorGeneric: "Fejl", googleError: "Google login mislykkedes" },
  fi: { training: "Treeni", health: "Terveys", logout: "Kirjaudu ulos", age: "Ikä", height: "Pituus (cm)", weight: "Paino (kg)", save: "Tallenna", bmi: "BMI", bmiChartTitle: "BMI vs. ihannealue", ideal: "Ihanne", you: "Sinä", underweight: "Alipaino", normal: "Normaali", overweight: "Ylipaino", obese: "Lihavuus", healthIntro: "Täytä tiedot laskeaksesi BMI:n.", language: "Kieli", signin: "Kirjaudu", signup: "Rekisteröidy", email: "Email", password: "Salasana", name: "Nimi", namePh: "Nimesi", emailPh: "sinä@email.com", passwordPh: "••••••••", continueGoogle: "Jatka Googlella", or: "tai", loading: "Ladataan...", brandTag: "suunnitelmasi, edistymisesi", accountCreated: "Tili luotu. Tarkista email.", errorGeneric: "Virhe", googleError: "Google-kirjautuminen epäonnistui" },
  cs: { training: "Trénink", health: "Zdraví", logout: "Odhlásit", age: "Věk", height: "Výška (cm)", weight: "Váha (kg)", save: "Uložit", bmi: "BMI", bmiChartTitle: "Vaše BMI vs. ideální rozsah", ideal: "Ideální", you: "Vy", underweight: "Podváha", normal: "Normální", overweight: "Nadváha", obese: "Obezita", healthIntro: "Vyplňte údaje pro výpočet BMI.", language: "Jazyk", signin: "Přihlásit", signup: "Registrovat", email: "Email", password: "Heslo", name: "Jméno", namePh: "Vaše jméno", emailPh: "vy@email.com", passwordPh: "••••••••", continueGoogle: "Pokračovat s Google", or: "nebo", loading: "Načítání...", brandTag: "váš plán, váš pokrok", accountCreated: "Účet vytvořen. Zkontrolujte email.", errorGeneric: "Chyba", googleError: "Přihlášení Google selhalo" },
  el: { training: "Προπόνηση", health: "Υγεία", logout: "Έξοδος", age: "Ηλικία", height: "Ύψος (εκ)", weight: "Βάρος (κιλά)", save: "Αποθήκευση", bmi: "ΔΜΣ", bmiChartTitle: "ΔΜΣ σας vs. ιδανικό εύρος", ideal: "Ιδανικό", you: "Εσείς", underweight: "Λιποβαρής", normal: "Φυσιολογικό", overweight: "Υπέρβαρος", obese: "Παχύσαρκος", healthIntro: "Συμπληρώστε δεδομένα για ΔΜΣ.", language: "Γλώσσα", signin: "Σύνδεση", signup: "Εγγραφή", email: "Email", password: "Κωδικός", name: "Όνομα", namePh: "Το όνομά σας", emailPh: "you@email.com", passwordPh: "••••••••", continueGoogle: "Συνέχεια με Google", or: "ή", loading: "Φόρτωση...", brandTag: "το πλάνο σας, η πρόοδός σας", accountCreated: "Λογαριασμός δημιουργήθηκε.", errorGeneric: "Σφάλμα", googleError: "Αποτυχία Google" },
  he: { training: "אימון", health: "בריאות", logout: "התנתק", age: "גיל", height: "גובה (ס\"מ)", weight: "משקל (ק\"ג)", save: "שמור", bmi: "BMI", bmiChartTitle: "ה-BMI שלך מול הטווח האידיאלי", ideal: "אידיאלי", you: "אתה", underweight: "תת משקל", normal: "תקין", overweight: "עודף משקל", obese: "השמנה", healthIntro: "מלא נתונים לחישוב BMI.", language: "שפה", signin: "כניסה", signup: "הרשמה", email: "אימייל", password: "סיסמה", name: "שם", namePh: "השם שלך", emailPh: "you@email.com", passwordPh: "••••••••", continueGoogle: "המשך עם Google", or: "או", loading: "טוען...", brandTag: "התוכנית שלך, ההתקדמות שלך", accountCreated: "החשבון נוצר. בדוק אימייל.", errorGeneric: "שגיאה", googleError: "כניסת Google נכשלה" },
  id: { training: "Latihan", health: "Kesehatan", logout: "Keluar", age: "Usia", height: "Tinggi (cm)", weight: "Berat (kg)", save: "Simpan", bmi: "IMT", bmiChartTitle: "IMT Anda vs. rentang ideal", ideal: "Ideal", you: "Anda", underweight: "Kurus", normal: "Normal", overweight: "Berlebih", obese: "Obesitas", healthIntro: "Isi data untuk menghitung IMT.", language: "Bahasa", signin: "Masuk", signup: "Daftar", email: "Email", password: "Kata sandi", name: "Nama", namePh: "Nama Anda", emailPh: "anda@email.com", passwordPh: "••••••••", continueGoogle: "Lanjutkan dengan Google", or: "atau", loading: "Memuat...", brandTag: "rencana Anda, kemajuan Anda", accountCreated: "Akun dibuat. Periksa email.", errorGeneric: "Error", googleError: "Login Google gagal" },
  th: { training: "การฝึก", health: "สุขภาพ", logout: "ออกจากระบบ", age: "อายุ", height: "ส่วนสูง (ซม.)", weight: "น้ำหนัก (กก.)", save: "บันทึก", bmi: "BMI", bmiChartTitle: "BMI ของคุณ vs. ช่วงที่เหมาะสม", ideal: "เหมาะสม", you: "คุณ", underweight: "น้ำหนักน้อย", normal: "ปกติ", overweight: "น้ำหนักเกิน", obese: "อ้วน", healthIntro: "กรอกข้อมูลเพื่อคำนวณ BMI", language: "ภาษา", signin: "เข้าสู่ระบบ", signup: "สมัคร", email: "อีเมล", password: "รหัสผ่าน", name: "ชื่อ", namePh: "ชื่อของคุณ", emailPh: "you@email.com", passwordPh: "••••••••", continueGoogle: "ดำเนินการต่อด้วย Google", or: "หรือ", loading: "กำลังโหลด...", brandTag: "แผนของคุณ ความก้าวหน้าของคุณ", accountCreated: "สร้างบัญชีแล้ว ตรวจสอบอีเมล", errorGeneric: "ข้อผิดพลาด", googleError: "Google ล้มเหลว" },
  vi: { training: "Tập luyện", health: "Sức khỏe", logout: "Đăng xuất", age: "Tuổi", height: "Chiều cao (cm)", weight: "Cân nặng (kg)", save: "Lưu", bmi: "BMI", bmiChartTitle: "BMI của bạn vs. lý tưởng", ideal: "Lý tưởng", you: "Bạn", underweight: "Thiếu cân", normal: "Bình thường", overweight: "Thừa cân", obese: "Béo phì", healthIntro: "Nhập dữ liệu để tính BMI.", language: "Ngôn ngữ", signin: "Đăng nhập", signup: "Đăng ký", email: "Email", password: "Mật khẩu", name: "Tên", namePh: "Tên của bạn", emailPh: "ban@email.com", passwordPh: "••••••••", continueGoogle: "Tiếp tục với Google", or: "hoặc", loading: "Đang tải...", brandTag: "kế hoạch của bạn, tiến bộ của bạn", accountCreated: "Tài khoản đã tạo. Kiểm tra email.", errorGeneric: "Lỗi", googleError: "Đăng nhập Google thất bại" },
  uk: { training: "Тренування", health: "Здоров'я", logout: "Вийти", age: "Вік", height: "Зріст (см)", weight: "Вага (кг)", save: "Зберегти", bmi: "ІМТ", bmiChartTitle: "Ваш ІМТ vs. ідеал", ideal: "Ідеал", you: "Ви", underweight: "Недовага", normal: "Норма", overweight: "Надмірна вага", obese: "Ожиріння", healthIntro: "Заповніть дані для розрахунку ІМТ.", language: "Мова", signin: "Увійти", signup: "Реєстрація", email: "Email", password: "Пароль", name: "Ім'я", namePh: "Ваше ім'я", emailPh: "ви@email.com", passwordPh: "••••••••", continueGoogle: "Продовжити з Google", or: "або", loading: "Завантаження...", brandTag: "ваш план, ваш прогрес", accountCreated: "Акаунт створено. Перевірте email.", errorGeneric: "Помилка", googleError: "Помилка Google" },
  ro: { training: "Antrenament", health: "Sănătate", logout: "Ieșire", age: "Vârstă", height: "Înălțime (cm)", weight: "Greutate (kg)", save: "Salvează", bmi: "IMC", bmiChartTitle: "IMC-ul tău vs. intervalul ideal", ideal: "Ideal", you: "Tu", underweight: "Subponderal", normal: "Normal", overweight: "Supraponderal", obese: "Obez", healthIntro: "Completează datele pentru a calcula IMC.", language: "Limbă", signin: "Conectare", signup: "Înregistrare", email: "Email", password: "Parolă", name: "Nume", namePh: "Numele tău", emailPh: "tu@email.com", passwordPh: "••••••••", continueGoogle: "Continuă cu Google", or: "sau", loading: "Se încarcă...", brandTag: "planul tău, progresul tău", accountCreated: "Cont creat. Verifică email.", errorGeneric: "Eroare", googleError: "Eșec Google" },
  hu: { training: "Edzés", health: "Egészség", logout: "Kijelentkezés", age: "Kor", height: "Magasság (cm)", weight: "Súly (kg)", save: "Mentés", bmi: "BMI", bmiChartTitle: "BMI vs. ideális tartomány", ideal: "Ideális", you: "Te", underweight: "Sovány", normal: "Normál", overweight: "Túlsúly", obese: "Elhízás", healthIntro: "Töltsd ki az adatokat a BMI-hez.", language: "Nyelv", signin: "Bejelentkezés", signup: "Regisztráció", email: "Email", password: "Jelszó", name: "Név", namePh: "Neved", emailPh: "te@email.com", passwordPh: "••••••••", continueGoogle: "Folytatás Google-lel", or: "vagy", loading: "Betöltés...", brandTag: "a terved, a haladásod", accountCreated: "Fiók létrehozva. Ellenőrizd az emailt.", errorGeneric: "Hiba", googleError: "Google bejelentkezés sikertelen" },
  bg: { training: "Тренировка", health: "Здраве", logout: "Изход", age: "Възраст", height: "Височина (см)", weight: "Тегло (кг)", save: "Запази", bmi: "ИТМ", bmiChartTitle: "Вашият ИТМ vs. идеален диапазон", ideal: "Идеален", you: "Вие", underweight: "Поднормено", normal: "Норма", overweight: "Наднормено", obese: "Затлъстяване", healthIntro: "Попълнете данните за ИТМ.", language: "Език", signin: "Вход", signup: "Регистрация", email: "Email", password: "Парола", name: "Име", namePh: "Вашето име", emailPh: "вие@email.com", passwordPh: "••••••••", continueGoogle: "Продължи с Google", or: "или", loading: "Зареждане...", brandTag: "вашият план, вашият напредък", accountCreated: "Акаунтът е създаден.", errorGeneric: "Грешка", googleError: "Google неуспешен" },
  ca: { training: "Entrenament", health: "Salut", logout: "Sortir", age: "Edat", height: "Alçada (cm)", weight: "Pes (kg)", save: "Desar", bmi: "IMC", bmiChartTitle: "El teu IMC vs. rang ideal", ideal: "Ideal", you: "Tu", underweight: "Pes baix", normal: "Normal", overweight: "Sobrepès", obese: "Obesitat", healthIntro: "Omple les dades per calcular l'IMC.", language: "Idioma", signin: "Entrar", signup: "Crear compte", email: "Email", password: "Contrasenya", name: "Nom", namePh: "El teu nom", emailPh: "tu@email.com", passwordPh: "••••••••", continueGoogle: "Continuar amb Google", or: "o", loading: "Carregant...", brandTag: "el teu pla, el teu progrés", accountCreated: "Compte creat. Revisa el correu.", errorGeneric: "Error", googleError: "No s'ha pogut iniciar amb Google" },
};

type Ctx = { lang: LangCode; setLang: (l: LangCode) => void; t: (k: keyof Dict) => string };
const I18nContext = createContext<Ctx | null>(null);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>("es");

  useEffect(() => {
    if (typeof window === "undefined") return;
    const saved = localStorage.getItem("lang") as LangCode | null;
    if (saved && T[saved]) setLangState(saved);
  }, []);

  const setLang = (l: LangCode) => {
    setLangState(l);
    if (typeof window !== "undefined") localStorage.setItem("lang", l);
  };

  const t = (k: keyof Dict) => T[lang]?.[k] ?? T.es[k] ?? (k as string);
  return <I18nContext.Provider value={{ lang, setLang, t }}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  const ctx = useContext(I18nContext);
  if (!ctx) throw new Error("useI18n must be inside I18nProvider");
  return ctx;
}
