/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated.plan'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated.nutrition'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated.health'
import { Route as AuthenticatedAiRoutineRouteImport } from './routes/_authenticated.ai-routine'
import { Route as AuthenticatedExerciseExerciseIdRouteImport } from './routes/_authenticated.exercise.$exerciseId'
import { Route as AuthenticatedDayDayIdRouteImport } from './routes/_authenticated.day.$dayId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiRoutineRoute = AuthenticatedAiRoutineRouteImport.update({
  id: '/ai-routine',
  path: '/ai-routine',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExerciseExerciseIdRoute =
  AuthenticatedExerciseExerciseIdRouteImport.update({
    id: '/exercise/$exerciseId',
    path: '/exercise/$exerciseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDayDayIdRoute = AuthenticatedDayDayIdRouteImport.update({
  id: '/day/$dayId',
  path: '/day/$dayId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-routine': typeof AuthenticatedAiRoutineRoute
  '/health': typeof AuthenticatedHealthRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/day/$dayId': typeof AuthenticatedDayDayIdRoute
  '/exercise/$exerciseId': typeof AuthenticatedExerciseExerciseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-routine': typeof AuthenticatedAiRoutineRoute
  '/health': typeof AuthenticatedHealthRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/day/$dayId': typeof AuthenticatedDayDayIdRoute
  '/exercise/$exerciseId': typeof AuthenticatedExerciseExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ai-routine': typeof AuthenticatedAiRoutineRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/day/$dayId': typeof AuthenticatedDayDayIdRoute
  '/_authenticated/exercise/$exerciseId': typeof AuthenticatedExerciseExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-routine'
    | '/health'
    | '/nutrition'
    | '/plan'
    | '/day/$dayId'
    | '/exercise/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-routine'
    | '/health'
    | '/nutrition'
    | '/plan'
    | '/day/$dayId'
    | '/exercise/$exerciseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ai-routine'
    | '/_authenticated/health'
    | '/_authenticated/nutrition'
    | '/_authenticated/plan'
    | '/_authenticated/day/$dayId'
    | '/_authenticated/exercise/$exerciseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-routine': {
      id: '/_authenticated/ai-routine'
      path: '/ai-routine'
      fullPath: '/ai-routine'
      preLoaderRoute: typeof AuthenticatedAiRoutineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exercise/$exerciseId': {
      id: '/_authenticated/exercise/$exerciseId'
      path: '/exercise/$exerciseId'
      fullPath: '/exercise/$exerciseId'
      preLoaderRoute: typeof AuthenticatedExerciseExerciseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/day/$dayId': {
      id: '/_authenticated/day/$dayId'
      path: '/day/$dayId'
      fullPath: '/day/$dayId'
      preLoaderRoute: typeof AuthenticatedDayDayIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAiRoutineRoute: typeof AuthenticatedAiRoutineRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedDayDayIdRoute: typeof AuthenticatedDayDayIdRoute
  AuthenticatedExerciseExerciseIdRoute: typeof AuthenticatedExerciseExerciseIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiRoutineRoute: AuthenticatedAiRoutineRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedDayDayIdRoute: AuthenticatedDayDayIdRoute,
  AuthenticatedExerciseExerciseIdRoute: AuthenticatedExerciseExerciseIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
